spring:
  application:
   name: LearnBuddy
  datasource:
    username: root
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/learnbuddy?serverTimezone=Asia/Shanghai
  profiles:
    active: local
server:
  port: 8080
jwt:
  access-expire: ${JWT_ACCESS_EXPIRE}
  SECRET: ${JWT_SECRET}
  jwt-iss: ${JWT_ISS}
  SUBJECT: ${JWT_SUBJECT}
security:
  white-list:
    - /user/login